name: geospatial-clustering
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9  # You can change the Python version as needed
  - planetary-computer=0.10.0
  - pystac-client=0.7.0
  - xarray=2023.0.0
  - rioxarray=0.13.0
  - numpy=1.23.4
  - dask=2023.6.0
  - dask-distributed=2023.6.0
  - pyproj=3.4.1
  - rasterio=1.3.5
  - shapely=2.0.1
  - requests=2.28.1
  - tqdm=4.64.1
  - matplotlib=3.6.2
  - scikit-learn=1.2.1
  - pip
  - pip:
      - xarray  # This is for rioxarray dependencies
